# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 16:16
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20170507_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0.0'), default_currency='GBP', max_digits=6, validators=[django.core.validators.MinValueValidator(djmoney.models.fields.MoneyPatched(10000, 'GBP')), django.core.validators.MaxValueValidator(djmoney.models.fields.MoneyPatched(100000, 'GBP'))]),
        ),
    ]
