# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 16:44
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20170507_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0.0'), default_currency='GBP', max_digits=6, validators=[django.core.validators.MinValueValidator(10000.0), django.core.validators.MaxValueValidator(100000.0)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_deadline',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date(2017, 6, 4)), django.core.validators.MaxValueValidator(datetime.date(2019, 5, 7))]),
        ),
    ]
