# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20170506_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='is_borrower',
            field=models.BooleanField(default=False),
        ),
    ]
