# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 17:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20170507_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address_two',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='postcode',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^([A-PR-UWYZ0-9][A-HK-Y0-9][AEHMNPRTVXY0-9]?[ABEHMNPRVWXY0-9]? {1,2}[0-9][ABD-HJLN-UW-Z]{2}|GIR 0AA)$', message='Postcode must be valid')]),
        ),
    ]
