# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 17:06
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_borrower_is_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, unique=True),
        ),
    ]
