# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 13:06
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20170509_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_deadline',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date(2017, 6, 10)), django.core.validators.MaxValueValidator(datetime.date(2019, 5, 13))]),
        ),
    ]
