# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20170506_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='rcn',
            new_name='crn',
        ),
    ]
