# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 21:07
from __future__ import unicode_literals

from django.db import migrations
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_auto_20170506_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='crn',
            field=loans.models.CRNField(primary_key=True, serialize=False, unique=True),
        ),
    ]
